title: Abdullah Ahmed H
description: Portfolio website
theme: minima
header_pages:
  - projects.md
  - blog.md
  - about.md

collections:
  projects:
    output: true

sass:
  style: compressed

minima:
  skin: dark
